version: '3.4'

services:
  passeio.web:
    image: ${DOCKER_REGISTRY-}passeioweb
    build:
      context: .
      dockerfile: Passeio.web/Dockerfile
    networks: 
      - frontend
  passeio.api:
    image: ${DOCKER_REGISTRY-}passeioapi
    build:
      context: .
      dockerfile: Passeio/Dockerfile
    networks: 
      - frontend
      - backend
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - backend
   # volumes:
      #- "/data/dbPasseio.mdf:/var/opt/mssql/data/dbPasseio.mdf"
      #- "/data/dbPasseio.ldf:/var/opt/mssql/data/dbPasseio.ldf"
      #- "C:\/Users\/02855130280\/source\/repos\/Passeio\/data:/var/opt/mssql/data"
      #- C:\/Users\/Alexandra Natacha\/source\/repos\/Passeio\/data:/var/opt/mssql/data"
      #- "/data:/var/opt/mssql/data"

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge