name: Build ASP.NET Core Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1' # Substitua pela versão do .NET Core que você está usando

    - name: Build with dotnet
      run: dotnet build Passeio.web/Passeio.web.csproj -c Release

    - name: Compile View
      run: dotnet aspnet-codegenerator razorpage -m Local -dc ApplicationDbContext -udl -outDir Passeio.web/Views/Local --referenceScriptLibraries

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: Passeio.web
